[package]
name = "inplace_it"
version = "0.3.5"
authors = ["Dmitry Demin <shepardiwe@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Place small arrays on the stack with a low-cost!"
repository = "https://github.com/NotIntMan/inplace_it"
readme = "README.md"

[dependencies]
